services:
  - type: web
    name: imarisha-loans
    env: python
    region: frankfurt
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt && flask db stamp b4c36442d5cd && flask db upgrade && python seed.py"
    startCommand: "cd backend && bash migrate_and_run.sh"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10
      - key: DATABASE_URL
        fromDatabase:
          name: imarisha-loans-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
